# Generated by Django 5.0.2 on 2024-05-08 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_portfolioitem_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioitem',
            name='image_alt_text',
            field=models.CharField(blank=True, help_text='Product Image Alternate Text', max_length=255),
        ),
    ]
