# Generated by Django 5.0.2 on 2024-04-28 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='buyer_note',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='digital_product',
            field=models.FileField(blank=True, null=True, upload_to='orders/products/'),
        ),
        migrations.AddField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('received', 'Received'), ('in_progress', 'In Progress'), ('finalized', 'Finalized')], default='received', max_length=20),
        ),
    ]
