# Generated by Django 5.0.2 on 2024-05-07 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_remove_order_address_order_address_line_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='address_line2',
            field=models.CharField(default='', max_length=255, verbose_name='Address Line 2'),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(default='', max_length=50, verbose_name='Phone Number'),
        ),
    ]
